version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
    command: sleep infinity
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://db:27017
    depends_on:
      - db
    networks:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - backend

volumes:
  mongodb-data:

networks:
  backend:
    driver: bridge
    attachable: true
